CREATE TABLE topics(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL,
    mensaje VARCHAR(600) NOT NULL UNIQUE,
    fecha DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    autor VARCHAR(50) NOT NULL,
    curso VARCHAR(50) NOT NULL
);